server {
    listen 443 ssl;
    server_name localhost marlonco.42.fr;
    ssl_certificate /etc/ssl/certs/ngninx-selfsigned.crt 
    ssl_key /etc/ssl/private/nginx-selfsigned.key

    location / {

    }

}
